os: linux
dist: bionic
sudo: false

language: c

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug   USE_FREEALUT=ON  USE_FREEGLUT=ON                            USE_GLFW=OFF USE_SDL2=OFF
  - BUILD_TYPE=Debug   USE_FREEALUT=ON  USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=OFF USE_GLFW=ON  USE_SDL2=OFF
  - BUILD_TYPE=Debug   USE_FREEALUT=ON  USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=ON  USE_GLFW=ON  USE_SDL2=OFF
  - BUILD_TYPE=Debug   USE_FREEALUT=ON  USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=OFF USE_GLFW=OFF USE_SDL2=ON
  - BUILD_TYPE=Debug   USE_FREEALUT=ON  USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=ON  USE_GLFW=OFF USE_SDL2=ON

  - BUILD_TYPE=Debug   USE_FREEALUT=OFF USE_FREEGLUT=ON                            USE_GLFW=OFF USE_SDL2=OFF
  - BUILD_TYPE=Debug   USE_FREEALUT=OFF USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=OFF USE_GLFW=ON  USE_SDL2=OFF
  - BUILD_TYPE=Debug   USE_FREEALUT=OFF USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=ON  USE_GLFW=ON  USE_SDL2=OFF
  - BUILD_TYPE=Debug   USE_FREEALUT=OFF USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=OFF USE_GLFW=OFF USE_SDL2=ON
  - BUILD_TYPE=Debug   USE_FREEALUT=OFF USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=ON  USE_GLFW=OFF USE_SDL2=ON

  - BUILD_TYPE=Release USE_FREEALUT=ON  USE_FREEGLUT=ON                            USE_GLFW=OFF USE_SDL2=OFF
  - BUILD_TYPE=Release USE_FREEALUT=ON  USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=OFF USE_GLFW=ON  USE_SDL2=OFF
  - BUILD_TYPE=Release USE_FREEALUT=ON  USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=ON  USE_GLFW=ON  USE_SDL2=OFF
  - BUILD_TYPE=Release USE_FREEALUT=ON  USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=OFF USE_GLFW=OFF USE_SDL2=ON
  - BUILD_TYPE=Release USE_FREEALUT=ON  USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=ON  USE_GLFW=OFF USE_SDL2=ON

  - BUILD_TYPE=Release USE_FREEALUT=OFF USE_FREEGLUT=ON                            USE_GLFW=OFF USE_SDL2=OFF
  - BUILD_TYPE=Release USE_FREEALUT=OFF USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=OFF USE_GLFW=ON  USE_SDL2=OFF
  - BUILD_TYPE=Release USE_FREEALUT=OFF USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=ON  USE_GLFW=ON  USE_SDL2=OFF
  - BUILD_TYPE=Release USE_FREEALUT=OFF USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=OFF USE_GLFW=OFF USE_SDL2=ON
  - BUILD_TYPE=Release USE_FREEALUT=OFF USE_FREEGLUT=OFF USE_FREEGLUT_FOR_TEXT=ON  USE_GLFW=OFF USE_SDL2=ON

addons:
  apt:
    packages:
      - libgl1-mesa-dev   # FreeGLUT
      - libglu1-mesa-dev  # FreeGLUT
      - libopenal-dev     # FreeALUT
      - libxcursor-dev    # GLFW
      - libxi-dev         # FreeGLUT & GLFW
      - libxinerama-dev   # GLFW
      - libxrandr-dev     # GLFW

install:
  - export EXTERNAL_DIR=$(pwd)/external
  - if [[ ${USE_FREEALUT} == ON ]]; then ./script/freealut.sh; fi
  - if [[ ${USE_FREEGLUT} == ON ]]; then ./script/freeglut.sh; fi
  - if [[ ${USE_GLFW} == ON ]]; then ./script/glfw.sh; fi
  - if [[ ${USE_SDL2} == ON ]]; then ./script/sdl2.sh; fi

script:
  - |
    cmake . -Bbuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                    -DSLIDINGPUZZLE_USE_FREEALUT=${USE_FREEALUT} \
                    -DSLIDINGPUZZLE_USE_FREEGLUT=${USE_FREEGLUT} \
                    -DSLIDINGPUZZLE_USE_FREEGLUT_FOR_TEXT=${USE_FREEGLUT_FOR_TEXT} \
                    -DSLIDINGPUZZLE_USE_GLFW=${USE_GLFW} \
                    -DSLIDINGPUZZLE_USE_SDL2=${USE_SDL2} \
                    -DSLIDINGPUZZLE_WARNINGS_AS_ERRORS=ON \
                    -DSNAKE_USE_FREEALUT=${USE_FREEALUT} \
                    -DSNAKE_USE_FREEGLUT=${USE_FREEGLUT} \
                    -DSNAKE_USE_FREEGLUT_FOR_TEXT=${USE_FREEGLUT_FOR_TEXT} \
                    -DSNAKE_USE_GLFW=${USE_GLFW} \
                    -DSNAKE_USE_SDL2=${USE_SDL2} \
                    -DSNAKE_WARNINGS_AS_ERRORS=ON \
                    -DVIDEOSTOP_USE_FREEALUT=${USE_FREEALUT} \
                    -DVIDEOSTOP_USE_FREEGLUT=${USE_FREEGLUT} \
                    -DVIDEOSTOP_USE_FREEGLUT_FOR_TEXT=${USE_FREEGLUT_FOR_TEXT} \
                    -DVIDEOSTOP_USE_GLFW=${USE_GLFW} \
                    -DVIDEOSTOP_USE_SDL2=${USE_SDL2} \
                    -DVIDEOSTOP_WARNINGS_AS_ERRORS=ON
  - cmake --build build
