os: linux
dist: bionic
sudo: false

language: c

compiler:
  - clang
  - gcc

env:
  # FreeGLUT Debug
  - BUILD_TYPE=Debug    USE_FREEGLUT=ON   USE_GLFW=OFF  USE_SDL2=OFF  USE_FREEGLUT_FOR_TEXT=ON  USE_FREEALUT_FOR_AUDIO=ON   USE_SDL2_FOR_AUDIO=OFF
  - BUILD_TYPE=Debug    USE_FREEGLUT=ON   USE_GLFW=OFF  USE_SDL2=OFF  USE_FREEGLUT_FOR_TEXT=ON  USE_FREEALUT_FOR_AUDIO=OFF  USE_SDL2_FOR_AUDIO=ON

  # GLFW Debug
  - BUILD_TYPE=Debug    USE_FREEGLUT=OFF  USE_GLFW=ON   USE_SDL2=OFF  USE_FREEGLUT_FOR_TEXT=ON  USE_FREEALUT_FOR_AUDIO=ON   USE_SDL2_FOR_AUDIO=OFF
  - BUILD_TYPE=Debug    USE_FREEGLUT=OFF  USE_GLFW=ON   USE_SDL2=OFF  USE_FREEGLUT_FOR_TEXT=ON  USE_FREEALUT_FOR_AUDIO=OFF  USE_SDL2_FOR_AUDIO=ON

  # SDL2 Debug
  - BUILD_TYPE=Debug    USE_FREEGLUT=OFF  USE_GLFW=OFF  USE_SDL2=ON   USE_FREEGLUT_FOR_TEXT=ON  USE_FREEALUT_FOR_AUDIO=ON   USE_SDL2_FOR_AUDIO=OFF
  - BUILD_TYPE=Debug    USE_FREEGLUT=OFF  USE_GLFW=OFF  USE_SDL2=ON   USE_FREEGLUT_FOR_TEXT=ON  USE_FREEALUT_FOR_AUDIO=OFF  USE_SDL2_FOR_AUDIO=ON

  # FreeGLUT Release
  - BUILD_TYPE=Release  USE_FREEGLUT=ON   USE_GLFW=OFF  USE_SDL2=OFF  USE_FREEGLUT_FOR_TEXT=ON  USE_FREEALUT_FOR_AUDIO=ON   USE_SDL2_FOR_AUDIO=OFF
  - BUILD_TYPE=Release  USE_FREEGLUT=ON   USE_GLFW=OFF  USE_SDL2=OFF  USE_FREEGLUT_FOR_TEXT=ON  USE_FREEALUT_FOR_AUDIO=OFF  USE_SDL2_FOR_AUDIO=ON

  # GLFW Release
  - BUILD_TYPE=Release  USE_FREEGLUT=OFF  USE_GLFW=ON   USE_SDL2=OFF  USE_FREEGLUT_FOR_TEXT=ON  USE_FREEALUT_FOR_AUDIO=ON   USE_SDL2_FOR_AUDIO=OFF
  - BUILD_TYPE=Release  USE_FREEGLUT=OFF  USE_GLFW=ON   USE_SDL2=OFF  USE_FREEGLUT_FOR_TEXT=ON  USE_FREEALUT_FOR_AUDIO=OFF  USE_SDL2_FOR_AUDIO=ON

  # SDL2 Release
  - BUILD_TYPE=Release  USE_FREEGLUT=OFF  USE_GLFW=OFF  USE_SDL2=ON   USE_FREEGLUT_FOR_TEXT=ON  USE_FREEALUT_FOR_AUDIO=ON   USE_SDL2_FOR_AUDIO=OFF
  - BUILD_TYPE=Release  USE_FREEGLUT=OFF  USE_GLFW=OFF  USE_SDL2=ON   USE_FREEGLUT_FOR_TEXT=ON  USE_FREEALUT_FOR_AUDIO=OFF  USE_SDL2_FOR_AUDIO=ON

addons:
  apt:
    packages:
      - libgl1-mesa-dev   # FreeGLUT
      - libglu1-mesa-dev  # FreeGLUT
      - libopenal-dev     # FreeALUT
      - libxcursor-dev    # GLFW
      - libxi-dev         # FreeGLUT & GLFW
      - libxinerama-dev   # GLFW
      - libxrandr-dev     # GLFW

install:
  - export DEPS_DIR=$(pwd)/deps
  - ./bootstrap.sh

script:
  - |
    cmake -S . -Bbuild \
          -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
          -DSLIDINGPUZZLE_USE_FREEGLUT=${USE_FREEGLUT} \
          -DSLIDINGPUZZLE_USE_GLFW=${USE_GLFW} \
          -DSLIDINGPUZZLE_USE_SDL2=${USE_SDL2} \
          -DSLIDINGPUZZLE_USE_FREEGLUT_FOR_TEXT=${USE_FREEGLUT_FOR_TEXT} \
          -DSLIDINGPUZZLE_USE_FREEALUT_FOR_AUDIO=${USE_FREEALUT_FOR_AUDIO} \
          -DSLIDINGPUZZLE_USE_SDL2_FOR_AUDIO=${USE_SDL2_FOR_AUDIO} \
          -DSLIDINGPUZZLE_WARNINGS_AS_ERRORS=ON \
          -DSNAKE_USE_FREEGLUT=${USE_FREEGLUT} \
          -DSNAKE_USE_GLFW=${USE_GLFW} \
          -DSNAKE_USE_SDL2=${USE_SDL2} \
          -DSNAKE_USE_FREEALUT_FOR_AUDIO=${USE_FREEALUT_FOR_AUDIO} \
          -DSNAKE_USE_SDL2_FOR_AUDIO=${USE_SDL2_FOR_AUDIO} \
          -DSNAKE_WARNINGS_AS_ERRORS=ON \
          -DVIDEOSTOP_USE_FREEGLUT=${USE_FREEGLUT} \
          -DVIDEOSTOP_USE_GLFW=${USE_GLFW} \
          -DVIDEOSTOP_USE_SDL2=${USE_SDL2} \
          -DVIDEOSTOP_USE_FREEGLUT_FOR_TEXT=${USE_FREEGLUT_FOR_TEXT} \
          -DVIDEOSTOP_USE_FREEALUT_FOR_AUDIO=${USE_FREEALUT_FOR_AUDIO} \
          -DVIDEOSTOP_USE_SDL2_FOR_AUDIO=${USE_SDL2_FOR_AUDIO} \
          -DVIDEOSTOP_WARNINGS_AS_ERRORS=ON
  - cmake --build build
  - cmake --build build --target package
