os: linux
dist: bionic
sudo: false

language: c

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
  - USE_FREEALUT=ON
  - USE_FREEALUT=OFF

addons:
  apt:
    packages:
      - libgl1-mesa-dev   # FreeGLUT
      - libglu1-mesa-dev  # FreeGLUT
      - libopenal-dev     # FreeALUT
      - libxcursor-dev    # GLFW
      - libxi-dev         # FreeGLUT & GLFW
      - libxinerama-dev   # GLFW
      - libxrandr-dev     # GLFW

install:
  - cd external
  - ./freealut.sh
  - ./freeglut.sh
  - ./glfw.sh
  - cd ..

script:
  - |
    cmake . -Bbuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                    -DALUT_ROOT_DIR=external \
                    -DSLIDINGPUZZLE_USE_FREEALUT=${USE_FREEALUT} \
                    -DSNAKE_USE_FREEALUT=${USE_FREEALUT} \
                    -DVIDEOSTOP_USE_FREEALUT=${USE_FREEALUT}
  - cmake --build build
