os: linux
dist: bionic
sudo: false

language: c

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug   USE_FREEALUT=ON  USE_FREEGLUT=ON  USE_GLFW=OFF
  - BUILD_TYPE=Debug   USE_FREEALUT=ON  USE_FREEGLUT=OFF USE_GLFW=ON
  - BUILD_TYPE=Debug   USE_FREEALUT=OFF USE_FREEGLUT=ON  USE_GLFW=OFF
  - BUILD_TYPE=Debug   USE_FREEALUT=OFF USE_FREEGLUT=OFF USE_GLFW=ON
  - BUILD_TYPE=Release USE_FREEALUT=ON  USE_FREEGLUT=ON  USE_GLFW=OFF
  - BUILD_TYPE=Release USE_FREEALUT=ON  USE_FREEGLUT=OFF USE_GLFW=ON
  - BUILD_TYPE=Release USE_FREEALUT=OFF USE_FREEGLUT=ON  USE_GLFW=OFF
  - BUILD_TYPE=Release USE_FREEALUT=OFF USE_FREEGLUT=OFF USE_GLFW=ON


addons:
  apt:
    packages:
      - libgl1-mesa-dev   # FreeGLUT
      - libglu1-mesa-dev  # FreeGLUT
      - libopenal-dev     # FreeALUT
      - libxcursor-dev    # GLFW
      - libxi-dev         # FreeGLUT & GLFW
      - libxinerama-dev   # GLFW
      - libxrandr-dev     # GLFW

install:
  - cd external
  - if [[ ${USE_FREEALUT} == ON ]]; then ./freealut.sh; fi
  - if [[ ${USE_FREEGLUT} == ON ]]; then ./freeglut.sh; fi
  - if [[ ${USE_GLFW} == ON ]]; then ./glfw.sh; fi
  - cd ..

script:
  - |
    cmake . -Bbuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                    -DALUT_ROOT_DIR=external \
                    -DSLIDINGPUZZLE_USE_FREEALUT=${USE_FREEALUT} \
                    -DSLIDINGPUZZLE_USE_FREEGLUT=${USE_FREEGLUT} \
                    -DSLIDINGPUZZLE_USE_GLFW=${USE_GLFW} \
                    -DSNAKE_USE_FREEALUT=${USE_FREEALUT} \
                    -DSNAKE_USE_FREEGLUT=${USE_FREEGLUT} \
                    -DSNAKE_USE_GLFW=${USE_GLFW} \
                    -DVIDEOSTOP_USE_FREEALUT=${USE_FREEALUT} \
                    -DVIDEOSTOP_USE_FREEGLUT=${USE_FREEGLUT} \
                    -DVIDEOSTOP_USE_GLFW=${USE_GLFW}
  - cmake --build build
