os: linux
dist: bionic
sudo: false

language: c

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug USE_FREEALUT=ON USE_FREEGLUT=ON
  - BUILD_TYPE=Debug USE_FREEALUT=OFF USE_FREEGLUT=ON
  - BUILD_TYPE=Release USE_FREEALUT=ON USE_FREEGLUT=ON
  - BUILD_TYPE=Release USE_FREEALUT=OFF USE_FREEGLUT=ON

addons:
  apt:
    packages:
      - libgl1-mesa-dev   # FreeGLUT
      - libglu1-mesa-dev  # FreeGLUT
      - libopenal-dev     # FreeALUT
      - libxcursor-dev    # GLFW
      - libxi-dev         # FreeGLUT & GLFW
      - libxinerama-dev   # GLFW
      - libxrandr-dev     # GLFW

install:
  - cd external
  - if [[ ${USE_FREEALUT} == ON ]]; then ./freealut.sh; fi
  - if [[ ${USE_FREEGLUT} == ON ]]; then ./freeglut.sh; fi
  - ./glfw.sh
  - cd ..

script:
  - |
    cmake . -Bbuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                    -DALUT_ROOT_DIR=external \
                    -DSLIDINGPUZZLE_USE_FREEALUT=${USE_FREEALUT} \
                    -DSLIDINGPUZZLE_USE_FREEGLUT=${USE_FREEGLUT} \
                    -DSNAKE_USE_FREEALUT=${USE_FREEALUT} \
                    -DSNAKE_USE_FREEGLUT=${USE_FREEGLUT} \
                    -DVIDEOSTOP_USE_FREEALUT=${USE_FREEALUT} \
                    -DVIDEOSTOP_USE_FREEGLUT=${USE_FREEGLUT}
  - cmake --build build
