execute_process(
  COMMAND git describe --always --tags --long
  OUTPUT_VARIABLE GIT_VERSION_LONG
  ERROR_QUIET
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(GIT_VERSION_LONG MATCHES "v[0-9]+\\.[0-9]+\\.[0-9]+-[0-9]+-g[0-9a-f]+")
  string(REGEX REPLACE "^v" "" GIT_VERSION_LONG ${GIT_VERSION_LONG})
  string(REPLACE "-g" "-" GIT_VERSION_LONG ${GIT_VERSION_LONG})
  string(REPLACE "-" "." GIT_VERSION_LONG ${GIT_VERSION_LONG})

  string(REPLACE "." ";" GIT_VERSIONS ${GIT_VERSION_LONG})
  list(GET GIT_VERSIONS 0 GIT_VERSION_MAJOR)
  list(GET GIT_VERSIONS 1 GIT_VERSION_MINOR)
  list(GET GIT_VERSIONS 2 GIT_VERSION_PATCH)
  list(GET GIT_VERSIONS 3 GIT_VERSION_COMMITS)
  list(GET GIT_VERSIONS 4 GIT_VERSION_HASH)
else()
  set(GIT_VERSION_MAJOR 0)
  set(GIT_VERSION_MINOR 0)
  set(GIT_VERSION_PATCH 0)
  set(GIT_VERSION_COMMITS 0)
  set(GIT_VERSION_HASH "ffffffff")

  set(GIT_VERSION_LONG "${GIT_VERSION_MAJOR}.${GIT_VERSION_MINOR}.${GIT_VERSION_PATCH}.${GIT_VERSION_COMMITS}.${GIT_VERSION_HASH}")
endif()

set(GIT_VERSION "${GIT_VERSION_MAJOR}.${GIT_VERSION_MINOR}.${GIT_VERSION_PATCH}")
